name = "acu-web"
compatibility_date = "2023-11-01"

[[r2_buckets]]
binding = "acu-web-assets"           # 必须和代码一致
bucket_name = "acu-web-assets"
preview_bucket_name = "acu-web-assets"

[site]
bucket = "./"                        # 静态资源目录

[[routes]]
pattern = "/ACU_videos/*"
script = "assets_handler"

[[routes]]
pattern = "/ACU_images/*"
script = "assets_handler"

[[routes]]
pattern = "/ACU_assets/ACU_fonts/*"
script = "assets_handler"

[[routes]]
pattern = "/ACU_assets/ACU_images/*"
script = "assets_handler"